services:
  - type: web
    name: url-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_API_KEY
        value: your_real_google_safe_browsing_api_key
