services:
  - type: web
    name: link-safety-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: MODE
        value: production
      - key: CUSTOM_API_KEY
        value: your-api-key-here
