services:
  - type: web
    name: virustotal-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: VT_API_KEY
        sync: false
