services:
  - type: web
    name: link-safety-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: MODE
        value: production
      - key: API_KEY
        value: 123456-abcDEF-secureKEY987
